### PR TITLE
Sanitizer updates

### PR DESCRIPTION
**Pull request by mapsam**
Working on #16 

* Updates to sanitizer to test `undefined` 
* Adds `-fno-sanitize-recover=all` to prevent us from building if errors exist

cc @springmeyer @GretaCB

### CODE REVIEW

**Comment by mapsam** [comment]
Looks like Linux is 👍  https://travis-ci.org/mapbox/hpp-skel/jobs/259486909

Waiting on OSX

**Comment by mapsam** [comment]
No errors!

**Comment by springmeyer** [comment]
👍  looks good @mapsam. Before merging I would recommend confirming that this is working by branching from this PR, adding some code to the test.cpp that will trigger the undefined behavior sanitizer, and confirming that the build fails. The branch can be throwaway, no need to merge anything but this branch.

**Comment by mapsam** [comment]
Thanks @springmeyer -great idea. Testing on a different branch with the same example from http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#usage shows the expected error:

```
./test-Debug
include/hello_world/exclaim.hpp:16:7: runtime error: signed integer overflow: 2147483647 + 2 cannot be represented in type 'int'
SUMMARY: AddressSanitizer: undefined-behavior include/hello_world/exclaim.hpp:16:7 in 
make: *** [test-Debug] Error 1
```

**Comment by springmeyer** [comment]
Nice work. I see it at https://travis-ci.org/mapbox/hpp-skel/jobs/259529312#L354. 👍

**Pull request merged**
